openapi: 3.0.0
info:
  title: types related to a person that are not fully stable yet
  version: 2.0-beta
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers: []
paths: {}
components:
  schemas:
    HouseholdRelationTypeCode:
      description: The type of relation of a household member to the household reference person, represented by a code assigned by the National Register
      type: integer
      minimum: 1
      maximum: 99
    CivilStatusTypeCode:
      description: The type of civil status of a person, represented by a code assigned by the National Register
      type: integer
      minimum: 1
      maximum: 99