swagger: "2.0"
info:
  title: types related to a person that are not fully stable yet
  version: 2.0-beta
paths: {}
definitions:
  HouseholdRelationTypeId:
    description: The type of relation of a household member to the household reference person, represented by a code assigned by the National Register
    type: integer
    minimum: 1
    maximum: 99
  CivilStateId:
    description: The civil state of a person, represented by a code assigned by the National Register
    type: integer
    minimum: 1
    maximum: 99